[위솝] models.py 작성
wecode-bootcamp-korea/Wesop-backend pull request #1
Opened 2021-01-13 08:02 UTC by donqlee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- user, products. orders 3개 앱 models.py 작성
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-01-13 11:27 UTC, jamessoun93 requested changes

2021-01-13 11:27 UTC, jamessoun93 commented on user/models.py
> +    first_name = models.CharField (max_length = 45)
```suggestion
    email      = models.CharField(max_length = 45)
    password   = models.CharField(max_length = 200)
    last_name  = models.CharField(max_length = 45)
    first_name = models.CharField(max_length = 45)
```

2021-01-13 11:27 UTC, jamessoun93 commented on user/models.py
> +    phone    = models.CharField (max_length = 45)
```suggestion
    user     = models.ForeignKey('User', on_delete=models.CASCADE)
    country  = models.CharField(max_length = 45)
    address  = models.CharField(max_length = 200)
    zip_code = models.IntegerField()
    phone    = models.CharField(max_length = 45)
```

2021-01-13 11:27 UTC, jamessoun93 commented on user/models.py
> +    country  = models.CharField (max_length = 45)
country 명은 create 될 때 넣는 사람이 정한대로 들어갈 수 있기때문에 정규화해주시는걸 추천드립니다.

2021-01-13 11:27 UTC, jamessoun93 commented on user/models.py
> +    zip_code = models.IntegerField
우선 소괄호가 빠져서 추가해주셔야 하고, zip_code 는 0 부터 시작할 수도 있으므로 IntegerField 는 적합하지 않습니다.

2021-01-13 11:27 UTC, jamessoun93 commented on orders/models.py
> +        return f'checkout_{self.pk}'
미완성 클래스인가요?

2021-01-13 11:27 UTC, jamessoun93 commented on orders/models.py
> +    checkout = models.ForeignKey('CheckOut',  on_delete=models.CASCADE, related_name='orders')
checkout 테이블에 아무 필드가 없는데 확인부탁드립니다.

2021-01-13 11:27 UTC, jamessoun93 commented on products/models.py
> +    video_url  = models.CharField(max_length=200)
이렇게되면 image 와 video 가 무조건 존재해야한다는 뜻인데, 이것보다는 url 을 주고 다른 컬럼으로 media type 을 지정해주시는게 어떨까 싶네요.

2021-01-13 11:27 UTC, jamessoun93 commented on products/models.py
> +
`M2M` 를 이렇게 각각 가지고 있는것보다, Product 테이블에서 `M2M` 필드를 전부가지고 있는게 더 관리하기도 편하고 쿼리셋 메소드를 활용하는데도 더 용이합니다~

2021-01-13 17:46 UTC, donqlee commented on user/models.py
> +    first_name = models.CharField (max_length = 45)
수정 진행 완료 👍

2021-01-13 17:46 UTC, donqlee commented on user/models.py
> +    phone    = models.CharField (max_length = 45)
수정 진행 완료 👍 (zip_code = models.CharField로 수정 진행)

2021-01-13 17:46 UTC, donqlee commented on user/models.py
> +    country  = models.CharField (max_length = 45)
수정 진행 🤔
class Country 생성 진행, 다음과 같이 수정이 맞는지 확인 부탁드립니다.

2021-01-13 17:46 UTC, donqlee commented on user/models.py
> +    zip_code = models.IntegerField
수정 진행 완료 👍 (zip_code = models.CharField로 수정 진행)

2021-01-13 17:46 UTC, donqlee commented on orders/models.py
> +        return f'checkout_{self.pk}'
수정 진행 🤔
checkout과 order, One to Many이므로 foreignkey 작성
다음과 같이 수정이 맞는지 확인 부탁드립니다.

2021-01-13 17:46 UTC, donqlee commented on orders/models.py
> +    checkout = models.ForeignKey('CheckOut',  on_delete=models.CASCADE, related_name='orders')
수정 진행🤔
checkout row 삭제 
다음과 같이 수정이 맞는지 확인 부탁드립니다.

2021-01-13 17:46 UTC, donqlee commented on products/models.py
> +    video_url  = models.CharField(max_length=200)
수정 진행🤔
다음과 같이 수정이 맞는지 확인 부탁드립니다.

2021-01-13 17:46 UTC, donqlee commented on products/models.py
> +
수정 진행🤔
다음과 같이 수정이 맞는지 확인 부탁드립니다.

2021-01-14 02:11 UTC, jamessoun93 requested changes

2021-01-14 02:11 UTC, jamessoun93 commented on user/models.py
> +    adress = models.OneToOneField('Address', on_delete=models.CASCADE)
country 에서 address 를 foreignkey 로 가지고 있는게 아니라 address 와 country 는 N:1 관계니까 address 에서 country를 가지고 있어야하겠죠?!

2021-01-14 04:46 UTC, donqlee commented on user/models.py
> +    adress = models.OneToOneField('Address', on_delete=models.CASCADE)
수정 진행🤔
다음과 같이 수정이 맞는지 확인 부탁드립니다.

2021-01-14 06:22 UTC, merged